######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 1 20:11:52 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += aboutdlg.ui mainwnd.ui passdlg.ui prefsdlg.ui
RESOURCES += abby.qrc
